version: "3.9"

services:
  3dcitydb-pg:
    image: tumgis/3dcitydb-web-map:v1.9.1
    container_name: 3dwebmap-viewer
    ports:
      - "8090:8000"
    env_file:
      - .env
    volumes:
      - 3dcitydb-viewer:/var/www/3dwebclient
      - 3dcitydb-tiles:/var/www/data
    restart: "on-failure"
    networks:
      - calcun-network

networks:
  calcun-network:
    name: calcun-network
    external: true
    driver: bridge

volumes:
  3dcitydb-viewer:
    name: calcun-3dcitydb-viewer-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./3dwebclient
  3dcitydb-tiles:
    name: calcun-3dcitydb-tiles-volume
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./3dcitydb_tiles_data