# Generated by Django 4.2.4 on 2023-09-27 13:20

from django.db import migrations
from django.contrib.auth.models import Group

def create_initial_roles(apps, schema_editor):
    reader = Group.objects.create(name="reader")
    admin = Group.objects.create(name="admin")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_initial_roles)
    ]
