#!/usr/bin/env bash

psql -d postgres -U $POSTGRES_USER -c "CREATE ROLE $POSTGRES_SU WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD '$POSTGRES_SUP';"

psql -d $POSTGRES_DB -U $POSTGRES_USER -c "CREATE EXTENSION IF NOT EXISTS postgis;"