FROM nginx:1.25.1-alpine

LABEL maintainer="spaciandd@gmail.com"
LABEL description="Development image for Nginx"

RUN rm /etc/nginx/conf.d/default.conf

COPY ./default.conf /etc/nginx/conf.d/default.conf