# Generated by Django 4.2.4 on 2024-01-15 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=50, null=True)),
                ('GlobalId', models.CharField(max_length=50, null=True)),
                ('AddressId', models.CharField(max_length=50, null=True)),
                ('Owner', models.CharField(max_length=50, null=True)),
                ('Tennant', models.CharField(max_length=50, null=True)),
                ('lod0', models.TextField(null=True)),
                ('lod1_X3D', models.TextField(null=True)),
                ('lod1_OBJ', models.TextField(null=True)),
                ('lod1_GLTF', models.TextField(null=True)),
                ('lod1_GLB', models.TextField(null=True)),
                ('BoundingBox', models.TextField(null=True)),
                ('Longitude', models.FloatField(null=True)),
                ('Latitude', models.FloatField(null=True)),
                ('Altitude', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
            ],
        ),
    ]
