# Generated by Django 4.2.4 on 2024-01-22 17:38

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('x3d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLookup',
            fields=[
                ('dataId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buildingIds', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, max_length=10), size=1000), size=1000)),
            ],
        ),
    ]
