# Generated by Django 4.2.4 on 2024-01-23 13:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x3d', '0002_assetlookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlookup',
            name='buildingIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), size=1000), size=1000),
        ),
        migrations.CreateModel(
            name='EventsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('eventDescription', models.TextField(max_length=500)),
                ('eventType', models.CharField(choices=[('0', 'Normal'), ('1', 'Medium'), ('2', 'Critical')], max_length=1)),
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x3d.buildings')),
            ],
        ),
    ]
