# Generated by Django 4.2.4 on 2024-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x3d', '0003_alter_assetlookup_buildingids_eventsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsdata',
            name='testField',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
