# Generated by Django 4.2.4 on 2024-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x3d', '0005_remove_eventsdata_testfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('group', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('value', models.BigIntegerField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
